#!/bin/bash

cd /Users/yulong/GitHub/study_case2/fvcom_files/0001/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/0002/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/0003/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/0004/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/0301/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/0302/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/0303/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/0304/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/1001/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/1002/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/1003/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/1004/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/2001/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/2002/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/2003/inp
sh ./makeFile.sh
cd /Users/yulong/GitHub/study_case2/fvcom_files/2004/inp
sh ./makeFile.sh